name: Deploy to Azure

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt | tee install_log.txt

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PasswordGenerator'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Startup Command
      run: |
        az webapp config set --name PasswordGenerator --resource-group uk-pr-passwordgenerator --startup-file "python -m pip install --upgrade pip && pip install -r requirements.txt && gunicorn -w 4 -b 0.0.0.0:80 app:app"

    - name: Upload Install Log
      uses: actions/upload-artifact@v3
      with:
        name: install-log
        path: install_log.txt